"""
Serial Rename Mixin — replace temporary serial codes with real scanned serials.

Applies when goods move from MID → whitelist warehouses (ORDST, ORDAP).
Only renames lots that were generated by this workflow (temp serials).

Key rules:
  - Picking must be 'done' (renaming happens after validation)
  - Destination must be in the warehouse whitelist
  - Only temp serials (matching workflow pattern) can be renamed
  - New serial must not already exist for the same product/company
  - Audit trail: original name stored in x_original_lot_name + chatter
  - Dry-run/preview is mandatory before apply
"""

from __future__ import annotations

import logging
import threading
from typing import Any

from .config import LotSerialConfig
from .serial_naming import build_plan_hash, is_temp_serial
from .workflow_fields import ORIGINAL_NAME_FIELD, WORKFLOW_CREATED_FIELD, assert_workflow_fields

logger = logging.getLogger(__name__)

# Lock registry for rename operations
_rename_locks: dict[int, threading.Lock] = {}
_rename_locks_lock = threading.Lock()


def _get_rename_lock(picking_id: int) -> threading.Lock:
    with _rename_locks_lock:
        if picking_id not in _rename_locks:
            _rename_locks[picking_id] = threading.Lock()
        return _rename_locks[picking_id]


class SerialRenameMixin:
    """Mixin for serial renaming (temp → real).

    Expects self.odoo to be an OdooClient instance (test server).
    """

    def preview_rename_serial(self, picking_id: int, rename_map: dict[str, str]) -> dict:
        """Preview serial renames for a completed picking.

        Args:
            picking_id: stock.picking ID (must be state='done')
            rename_map: {old_serial_name: new_serial_name, ...}

        Returns:
            {
                "picking": {id, name, state, dest_warehouse},
                "will_rename": [{lot_id, old_name, new_name, product_name}],
                "will_skip": [{old_name, reason}],
                "errors": [str]
            }
        """
        return self._do_rename_preview(picking_id, rename_map)

    def apply_rename_serial(
        self, picking_id: int, rename_map: dict[str, str], expected_plan_hash: str | None = None
    ) -> dict:
        """Apply serial renames with audit trail.

        Thread-safe per picking_id.

        Returns:
            {
                "picking_id": int,
                "renamed": [{lot_id, old_name, new_name, product_name}],
                "skipped": [...],
                "errors": [str]
            }
        """
        lock = _get_rename_lock(picking_id)
        if not lock.acquire(blocking=False):
            return {
                "picking_id": picking_id,
                "renamed": [],
                "skipped": [],
                "errors": ["Picking rename is already being processed. Please wait."],
            }
        try:
            return self._do_rename_apply(picking_id, rename_map, expected_plan_hash)
        finally:
            lock.release()

    # ─── Internal Implementation ────────────────────────────────

    def _do_rename_preview(self, picking_id: int, rename_map: dict[str, str]) -> dict:
        errors: list[str] = []
        will_rename: list[dict] = []
        will_skip: list[dict] = []

        if not rename_map:
            return {
                "picking": {"id": picking_id},
                "will_rename": [],
                "will_skip": [],
                "errors": ["rename_map is empty — nothing to rename"],
            }

        # 1. Fetch picking
        pickings = self.odoo.search_read(
            "stock.picking",
            [["id", "=", picking_id]],
            fields=[
                "id", "name", "state", "picking_type_code",
                "location_id", "location_dest_id", "company_id",
            ],
            limit=1,
        )
        if not pickings:
            return {
                "picking": {"id": picking_id},
                "will_rename": [],
                "will_skip": [],
                "errors": [f"Picking ID {picking_id} not found"],
            }

        picking = pickings[0]

        try:
            assert_workflow_fields(self.odoo)
        except Exception as error:
            return {
                "picking": {"id": picking_id, "name": picking["name"]},
                "will_rename": [], "will_skip": [], "errors": [str(error)],
            }

        # Validate state == done
        if picking["state"] != "done":
            return {
                "picking": {"id": picking_id, "name": picking["name"]},
                "will_rename": [],
                "will_skip": [],
                "errors": [
                    f"Picking {picking['name']} state is '{picking['state']}'. "
                    f"Serial rename only applies to completed ('done') pickings."
                ],
            }

        # 2. Check destination warehouse is in whitelist
        dest_warehouse_code = self._resolve_warehouse_code(picking)
        if dest_warehouse_code not in LotSerialConfig.WHITELIST_WAREHOUSES:
            return {
                "picking": {
                    "id": picking_id,
                    "name": picking["name"],
                    "dest_warehouse": dest_warehouse_code,
                },
                "will_rename": [],
                "will_skip": [],
                "errors": [
                    f"Destination warehouse '{dest_warehouse_code}' is not in "
                    f"the whitelist: {LotSerialConfig.WHITELIST_WAREHOUSES}. "
                    f"Serial rename is only allowed for: "
                    f"{', '.join(LotSerialConfig.WHITELIST_WAREHOUSES)}."
                ],
            }

        source_warehouse_code = self._resolve_warehouse_code(picking, source=True)
        if source_warehouse_code not in LotSerialConfig.SOURCE_WAREHOUSES:
            return {
                "picking": {"id": picking_id, "name": picking["name"]},
                "will_rename": [], "will_skip": [],
                "errors": [
                    f"Source warehouse '{source_warehouse_code}' is not allowed. "
                    f"Only transfers from {', '.join(LotSerialConfig.SOURCE_WAREHOUSES)} can rename serials."
                ],
            }

        # Get company_id
        company_id = (
            picking["company_id"][0]
            if isinstance(picking.get("company_id"), (list, tuple))
            else picking.get("company_id", 1)
        )

        # 3. Fetch move lines for this picking
        move_lines = self.odoo.search_read(
            "stock.move.line",
            [["picking_id", "=", picking_id]],
            fields=["id", "product_id", "lot_id", "lot_name"],
        )

        lot_records = self.odoo.read(
            "stock.lot",
            [
                ml["lot_id"][0] if isinstance(ml.get("lot_id"), (list, tuple)) else ml.get("lot_id")
                for ml in move_lines if ml.get("lot_id")
            ],
            fields=["name", WORKFLOW_CREATED_FIELD],
        )
        lot_by_id = {lot["id"]: lot for lot in lot_records}

        # Build a mapping of serial_name → move_line info
        lot_ids_in_picking = set()
        lot_name_to_info: dict[str, dict] = {}
        for ml in move_lines:
            if ml.get("lot_id"):
                lid = (
                    ml["lot_id"][0]
                    if isinstance(ml["lot_id"], (list, tuple))
                    else ml["lot_id"]
                )
                lot_ids_in_picking.add(lid)
                lot_display = (
                    ml["lot_id"][1]
                    if isinstance(ml["lot_id"], (list, tuple))
                    else ml.get("lot_name", "")
                )
                lot_name_to_info[lot_display] = {
                    "lot_id": lid,
                    "move_line_id": ml["id"],
                    "product_id": (
                        ml["product_id"][0]
                        if isinstance(ml["product_id"], (list, tuple))
                        else ml["product_id"]
                    ),
                    "product_name": (
                        ml["product_id"][1]
                        if isinstance(ml["product_id"], (list, tuple)) and len(ml["product_id"]) > 1
                        else str(ml["product_id"])
                    ),
                }

        # 4. Validate each rename
        for old_name, new_name in rename_map.items():
            # Check old_name exists in this picking
            if old_name not in lot_name_to_info:
                will_skip.append({
                    "old_name": old_name,
                    "new_name": new_name,
                    "reason": f"Serial '{old_name}' not found in picking {picking['name']}",
                })
                continue

            info = lot_name_to_info[old_name]

            lot_record = lot_by_id.get(info["lot_id"], {})
            if not lot_record.get(WORKFLOW_CREATED_FIELD):
                will_skip.append({
                    "old_name": old_name, "new_name": new_name,
                    "reason": "Serial was not created by the Lot/Serial workflow.",
                })
                continue

            # Check it's a temp serial
            if not is_temp_serial(old_name):
                will_skip.append({
                    "old_name": old_name,
                    "new_name": new_name,
                    "reason": (
                        f"Serial '{old_name}' is not a temp serial generated "
                        f"by this workflow. Only temp serials can be renamed."
                    ),
                })
                continue

            # Validate new_name is not empty
            if not new_name or not new_name.strip():
                errors.append(f"New serial name for '{old_name}' is empty")
                continue

            new_name = new_name.strip()

            if new_name == old_name:
                will_skip.append({"old_name": old_name, "new_name": new_name, "reason": "New serial is unchanged"})
                continue

            # Check new_name doesn't already exist
            existing = self.odoo.search(
                "stock.lot",
                [
                    ["name", "=", new_name],
                    ["product_id", "=", info["product_id"]],
                    ["company_id", "=", company_id],
                ],
                limit=1,
            )
            if existing:
                errors.append(
                    f"New serial '{new_name}' already exists for product "
                    f"{info['product_name']} (lot ID: {existing[0]})"
                )
                continue

            will_rename.append({
                "lot_id": info["lot_id"],
                "old_name": old_name,
                "new_name": new_name,
                "product_id": info["product_id"],
                "product_name": info["product_name"],
            })

        duplicate_targets = set()
        for item in will_rename:
            key = (item["product_id"], item["new_name"])
            if key in duplicate_targets:
                errors.append(f"New serial '{item['new_name']}' appears more than once for the same product")
            duplicate_targets.add(key)

        result = {
            "picking": {
                "id": picking_id,
                "name": picking["name"],
                "state": picking["state"],
                "dest_warehouse": dest_warehouse_code,
            },
            "will_rename": will_rename,
            "will_skip": will_skip,
            "errors": errors,
        }
        result["plan_hash"] = build_plan_hash("rename", picking_id, will_rename)
        return result

    def _do_rename_apply(
        self, picking_id: int, rename_map: dict[str, str], expected_plan_hash: str | None
    ) -> dict:
        preview = self._do_rename_preview(picking_id, rename_map)

        if preview.get("errors"):
            return {
                "picking_id": picking_id,
                "renamed": [],
                "skipped": preview.get("will_skip", []),
                "errors": preview["errors"],
            }

        if expected_plan_hash is not None and expected_plan_hash != preview.get("plan_hash"):
            return {
                "picking_id": picking_id, "renamed": [],
                "skipped": preview.get("will_skip", []),
                "errors": ["Preview is missing or stale. Preview again and send its plan_hash to Apply."],
            }

        if not preview.get("will_rename"):
            return {
                "picking_id": picking_id,
                "renamed": [],
                "skipped": preview.get("will_skip", []),
                "errors": ["No serials to rename after validation"],
            }

        renamed = []
        errors = []
        audit_field = ORIGINAL_NAME_FIELD
        use_chatter = LotSerialConfig.AUDIT_FALLBACK_CHATTER

        for item in preview["will_rename"]:
            lot_id = item["lot_id"]
            old_name = item["old_name"]
            new_name = item["new_name"]

            try:
                # 1. Audit must succeed before a name is changed. A chatter
                # message is extra information, never an audit substitute.
                self.odoo.write("stock.lot", [lot_id], {audit_field: old_name})
                audit_written = True
                logger.info(f"[LotSerial] Audit: {audit_field}='{old_name}' on lot {lot_id}")

                # 2. Rename the lot
                self.odoo.write("stock.lot", [lot_id], {
                    "name": new_name,
                })

                # 3. Post chatter message for traceability
                if use_chatter:
                    try:
                        self.odoo.execute(
                            "stock.lot",
                            "message_post",
                            [lot_id],
                            {
                                "body": (
                                    f"<p><b>Serial Renamed</b><br/>"
                                    f"Old: <code>{old_name}</code><br/>"
                                    f"New: <code>{new_name}</code><br/>"
                                    f"Picking: {preview['picking'].get('name', picking_id)}</p>"
                                ),
                                "message_type": "comment",
                                "subtype_xmlid": "mail.mt_note",
                            },
                        )
                    except Exception as chat_err:
                        logger.warning(
                            f"[LotSerial] Failed to post chatter on lot {lot_id}: {chat_err}"
                        )

                renamed.append({
                    "lot_id": lot_id,
                    "old_name": old_name,
                    "new_name": new_name,
                    "product_name": item["product_name"],
                    "audit_written": audit_written,
                })

                logger.info(
                    f"[LotSerial] Renamed lot {lot_id}: '{old_name}' → '{new_name}'"
                )

            except Exception as e:
                errors.append(
                    f"Failed to rename lot {lot_id} ('{old_name}' → '{new_name}'): {e}"
                )
                logger.exception(f"[LotSerial] Rename error: {e}")
                for changed in reversed(renamed):
                    try:
                        self.odoo.write("stock.lot", [changed["lot_id"]], {
                            "name": changed["old_name"], audit_field: False,
                        })
                    except Exception as rollback_error:
                        errors.append(f"Rollback failed for lot {changed['lot_id']}: {rollback_error}")
                return {
                    "picking_id": picking_id,
                    "renamed": [],
                    "skipped": preview.get("will_skip", []),
                    "errors": errors,
                }

        return {
            "picking_id": picking_id,
            "renamed": renamed,
            "skipped": preview.get("will_skip", []),
            "errors": errors,
        }

    # ─── Helpers ─────────────────────────────────────────────────

    def _resolve_warehouse_code(self, picking: dict, source: bool = False) -> str:
        """Resolve the destination warehouse code from picking's location_dest_id.

        Traverses location → warehouse mapping to get the warehouse code.
        Falls back to location name if warehouse lookup fails.
        """
        dest_loc = picking.get("location_id" if source else "location_dest_id")
        if not dest_loc:
            return "UNKNOWN"

        loc_id = (
            dest_loc[0]
            if isinstance(dest_loc, (list, tuple))
            else dest_loc
        )

        # Try to find warehouse via stock.location → warehouse_id
        # In Odoo, stock.warehouse has lot_stock_id pointing to location
        warehouses = self.odoo.search_read(
            "stock.warehouse",
            [["lot_stock_id", "=", loc_id]],
            fields=["code", "name"],
            limit=1,
        )
        if warehouses:
            return warehouses[0].get("code", "UNKNOWN")

        # Fallback: walk up location hierarchy
        locations = self.odoo.search_read(
            "stock.location",
            [["id", "=", loc_id]],
            fields=["id", "name", "location_id", "warehouse_id"],
            limit=1,
        )
        if locations and locations[0].get("warehouse_id"):
            wh_id = (
                locations[0]["warehouse_id"][0]
                if isinstance(locations[0]["warehouse_id"], (list, tuple))
                else locations[0]["warehouse_id"]
            )
            wh = self.odoo.search_read(
                "stock.warehouse",
                [["id", "=", wh_id]],
                fields=["code"],
                limit=1,
            )
            if wh:
                return wh[0].get("code", "UNKNOWN")

        # Last resort: use location name
        if locations:
            return locations[0].get("name", "UNKNOWN")

        return "UNKNOWN"
